# Generated by Django 3.0.2 on 2020-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainActionStatics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('tv_search_title', models.IntegerField(verbose_name='tv_search_title')),
                ('tv_unknown_search', models.IntegerField(verbose_name='tv_unknown_search')),
                ('tv_open_search', models.IntegerField(verbose_name='tv_open_search')),
                ('tv_play_title', models.IntegerField(verbose_name='tv_play_title')),
            ],
        ),
    ]
